server:
  port: 8097
spring:
  cloud:
    gateway:
      routes:
        # Ruta específica para login en configuracion-service (acceso sin token)
        - id: configuracion-service-login
          uri: http://localhost:8081
          predicates:
            - Path=/login
          filters:
            - RemoveRequestHeader=Authorization # Opcional: elimina el header de autorización para esta ruta

        # Rutas protegidas para todas las demás APIs en configuracion-service
        - id: configuracion-service-protected
          uri: http://localhost:8081
          predicates:
            - Path=/configuracion/**
          filters:
            - TokenRelay # Reenvía el token si es válido

        # Rutas protegidas para todas las APIs en inventario-service
        - id: inventario-service
          uri: http://localhost:8082
          predicates:
            - Path=/inventario/**
          filters:
            - TokenRelay # Reenvía el token si es válido

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8097/auth
logging:
  level:
    root: INFO
    com.facci: DEBUG
  file:
    name: /var/logs/gateway-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
