# Redirigir HTTP a HTTPS
server {
    listen 80;
    server_name 144.126.208.53;  
	# Cambia esto por tu IP pública o tu dominio

    # Redirigir a HTTPS
    return 301 https://$host$request_uri;
}

# Configuración HTTPS
server {
    listen 443 ssl;
    server_name 144.126.208.53;

    # Certificados SSL
    ssl_certificate /etc/nginx/certs/certificado.crt;
    ssl_certificate_key /etc/nginx/certs/certificado.key;

    # Seguridad SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Ruta de la aplicación Angular
    root /usr/share/nginx/html;
    index index.html;

    # Configurar las rutas
    location /api/ {
        proxy_pass https://gateway-service:8097/;
        proxy_ssl_verify off;
        proxy_ssl_session_reuse off;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Logs (opcional)
    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}
