server:
  port: 8099

spring:
  datasource:
    url: jdbc:sqlserver://host.docker.internal:1433;databaseName=facci_configuracion;encrypt=true;trustServerCertificate=true
    username: sa
    password: realhulk97
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: administrador
      password: $2a$10$5Kndd1j0JbfdAFSuU0GTkO4PradBmrcPfMhD1u8kMkJdxP75k7n.O
logging:
  level:
    root: INFO
    com.facci: DEBUG
    org.springframework.security: WARN
  file:
    name: configuracion-service/logs/configuracion-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
jwt:
  secret: $2a$10$5Kndd1j0JbfdAFSuU0GTkO4PradBmrcPfMhD1u8kMkJdxP75k7n.O
  expiration: 86400000
correo:
  perfil: Monitoreo
  portal: "https://facci-inventario/login"