server:
  port: 8098

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=facci_inventario;encrypt=true;trustServerCertificate=true
    username: sa
    password: Alt!ora2015
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: INFO
    com.facci: DEBUG
  file:
    name: /var/logs/inventario-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
jwt:
  secret: $2a$10$vl2reM1tzZoGoMwRxymMneiNjyUqWiCdT4.fFMZbL2nFZNSZo8csy
  expiration: 86400000

articulo:
  carpeta-imagenes: C:/imagenes/