server:
  port: 8098

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=facci_inventario;encrypt=true;trustServerCertificate=true
    username: sa
    password: Alt!ora2015
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true # Formatea las consultas SQL
      use_sql_comments: true # Agrega comentarios a las consultas
      highlight_sql: true # Resalta las consultas en los logs
      show_sql: true # Muestra las consultas SQL
    show-sql: true
logging:
  level:
    root: INFO
    com.facci: DEBUG
  file:
    name: inventario-service/logs/inventario-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
jwt:
  secret: $2a$10$vl2reM1tzZoGoMwRxymMneiNjyUqWiCdT4.fFMZbL2nFZNSZo8csy
  expiration: 86400000

articulo:
  carpeta-archivos: C:/archivos/

configuracion-service:
  url: http://localhost:8099